import { ChangeEvent, useEffect, useMemo, useRef, useState } from "react";
import { LOCAL_EXERCISES, generateLocalExerciseFrames, getExerciseTemplate, type ExerciseKey, type FrameCount } from "./local-generator";
import { CATEGORIES, buildGif, deleteGif, exportLibraryZip, fileToDataUrl, frameDuration, listSaved, playbackFor, saveGif, shareBytes, slugify, split2x2, type Frame, type LoopMode, type SavedGif, type Settings } from "./original-mode-core";
import "./original-mode.css";

export function OriginalModeApp(){
  const [mode,setMode]=useState<"original"|"draft">("original");
  const [name,setName]=useState("Elevação de pernas"),[category,setCategory]=useState("core"),[frames,setFrames]=useState<Frame[]>([]);
  const [loopMode,setLoopMode]=useState<LoopMode>("ping-pong"),[delay,setDelay]=useState(650),[startPause,setStartPause]=useState(300),[endPause,setEndPause]=useState(300),[size,setSize]=useState(512);
  const [previewIndex,setPreviewIndex]=useState(0),[working,setWorking]=useState(false),[saved,setSaved]=useState<SavedGif[]>([]),[message,setMessage]=useState("Modo Original: importe nossos quadros bonitos e transforme em GIF.");
  const [localExercise,setLocalExercise]=useState<ExerciseKey>("leg-raise"),[frameCount,setFrameCount]=useState<FrameCount>(8);
  const collageInput=useRef<HTMLInputElement>(null),framesInput=useRef<HTMLInputElement>(null);
  const slug=useMemo(()=>slugify(name)||"exercicio",[name]);
  const settings:Settings={loopMode,delay,startPause,endPause,size};
  const playback=useMemo(()=>playbackFor(frames,loopMode),[frames,loopMode]);
  const cycleMs=useMemo(()=>playback.reduce((t,f)=>t+frameDuration(f,frames,settings),0),[playback,frames,loopMode,delay,startPause,endPause,size]);

  useEffect(()=>{listSaved().then(setSaved).catch(()=>undefined)},[]);
  useEffect(()=>{if(!playback.length)return;const f=playback[previewIndex%playback.length];const timer=window.setTimeout(()=>setPreviewIndex(i=>(i+1)%playback.length),frameDuration(f,frames,settings));return()=>clearTimeout(timer)},[previewIndex,playback,frames,loopMode,delay,startPause,endPause,size]);

  async function importCollage(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setWorking(true);try{setFrames(await split2x2(await fileToDataUrl(file)));setPreviewIndex(0);setMessage("Colagem 2×2 recortada em 4 quadros. Confira a ordem.")}catch(err){setMessage(`Erro: ${err instanceof Error?err.message:String(err)}`)}finally{setWorking(false);e.target.value=""}}
  async function importFrames(e:ChangeEvent<HTMLInputElement>){const files=Array.from(e.target.files??[]);if(!files.length)return;setWorking(true);try{const next=await Promise.all(files.map(async(f,i)=>({id:crypto.randomUUID(),name:`frame-${i+1}`,dataUrl:await fileToDataUrl(f)})));setFrames(next);setPreviewIndex(0);setMessage(`${next.length} quadros originais importados.`)}finally{setWorking(false);e.target.value=""}}
  function normalize(list:Frame[]){return list.map((f,i)=>({...f,name:`frame-${i+1}`}))}
  function move(index:number,direction:-1|1){const target=index+direction;if(target<0||target>=frames.length)return;setFrames(cur=>{const c=[...cur];[c[index],c[target]]=[c[target],c[index]];return normalize(c)});setPreviewIndex(0)}
  function duplicate(index:number){setFrames(cur=>{const c=[...cur];c.splice(index+1,0,{...c[index],id:crypto.randomUUID()});return normalize(c)});setPreviewIndex(0)}
  function remove(id:string){setFrames(cur=>normalize(cur.filter(f=>f.id!==id)));setPreviewIndex(0)}
  function selectDraft(value:ExerciseKey){setLocalExercise(value);const t=getExerciseTemplate(value);setName(t.name);setCategory(t.category)}
  async function generateDraft(){setWorking(true);try{const t=getExerciseTemplate(localExercise);const f=await generateLocalExerciseFrames(localExercise,frameCount);setName(t.name);setCategory(t.category);setFrames(f);setPreviewIndex(0);setMessage("Rascunho gerado. Ele serve só para planejar o movimento; o visual final vem do Modo Original.")}finally{setWorking(false)}}
  async function generateFinal(){setWorking(true);setMessage("Gerando GIF final...");try{const bytes=await buildGif(frames,settings);const item:SavedGif={id:crypto.randomUUID(),name,slug,category,createdAt:new Date().toISOString(),bytes,frames:frames.map(f=>({name:f.name,dataUrl:f.dataUrl})),settings};await saveGif(item);setSaved(await listSaved());setMessage(`Pronto: ${slug}.gif • ${frames.length} quadros • ciclo ~${(cycleMs/1000).toFixed(1)}s`);await shareBytes(bytes,`${slug}.gif`)}catch(err){setMessage(`Erro: ${err instanceof Error?err.message:String(err)}`)}finally{setWorking(false)}}
  async function exportZip(){if(!saved.length){setMessage("Gere pelo menos um GIF primeiro.");return}setWorking(true);try{await shareBytes(await exportLibraryZip(saved),"projeto-trincado-original-pack.zip");setMessage("ZIP completo com GIFs, quadros e metadados pronto.")}finally{setWorking(false)}}

  return <div className="v5-app">
    <header className="v5-header"><div><small>PROJETO TRINCADO</small><h1>GIF Maker Original</h1><p>Use nossos próprios quadros, anime no celular e exporte tudo organizado.</p></div><span>v0.5</span></header>
    <main>
      <nav className="mode-tabs"><button className={mode==="original"?"active":""} onClick={()=>{setMode("original");setMessage("Modo Original: importe nossos quadros bonitos e transforme em GIF.")}}>★ Modo Original</button><button className={mode==="draft"?"active draft":""} onClick={()=>{setMode("draft");setMessage("Modo Rascunho é experimental e não representa o visual final.")}}>Rascunho experimental</button></nav>

      {mode==="original"?<>
        <section className="card hero"><div className="title-row"><div><small>MODO PRINCIPAL</small><h2>1. Imagens originais</h2></div><span>FINAL</span></div><p className="muted">O app não desenha bonecos aqui. Importe as imagens bonitas que criarmos e ele cuida do recorte, ordem, animação e GIF.</p><div className="import-grid"><button className="import-main" onClick={()=>collageInput.current?.click()}>▦ Importar colagem 2×2<small>Recorta 4 quadros sozinho</small></button><button className="import-alt" onClick={()=>framesInput.current?.click()}>▣ Importar pack de quadros<small>4, 6, 8 ou mais imagens</small></button></div><input ref={collageInput} hidden type="file" accept="image/*" onChange={importCollage}/><input ref={framesInput} hidden type="file" accept="image/*" multiple onChange={importFrames}/></section>
        <section className="card form-grid"><label>Nome do exercício<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Categoria<select value={category} onChange={e=>setCategory(e.target.value)}>{CATEGORIES.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><div className="path">Destino: <b>{category}/{slug}/{slug}.gif</b></div></section>
      </>:<section className="card draft-card"><div className="title-row"><div><small>EXPERIMENTAL</small><h2>Rascunho de movimento</h2></div><span>RASCUNHO</span></div><p className="muted">Serve só para visualizar posições. Não use esse desenho como visual final.</p><div className="two-col"><label>Exercício<select value={localExercise} onChange={e=>selectDraft(e.target.value as ExerciseKey)}>{LOCAL_EXERCISES.map(i=><option value={i.key} key={i.key}>{i.name}</option>)}</select></label><label>Quadros<select value={frameCount} onChange={e=>setFrameCount(Number(e.target.value) as FrameCount)}><option value="4">4</option><option value="6">6</option><option value="8">8</option></select></label></div><button className="draft-btn" disabled={working} onClick={generateDraft}>{working?"Gerando...":"Gerar rascunho"}</button></section>}

      <section className="card"><div className="section-head"><div><h2>2. Organizar quadros</h2><p className="muted">A ordem abaixo será usada na animação.</p></div>{frames.length>0&&<button className="clear" onClick={()=>{setFrames([]);setPreviewIndex(0)}}>Limpar</button>}</div>{!frames.length?<div className="empty">Importe uma colagem ou um pack para começar.</div>:<div className="frames">{frames.map((f,i)=><article key={f.id}><img src={f.dataUrl} alt={`Quadro ${i+1}`}/><strong>{i+1}</strong><div className="frame-actions"><button disabled={i===0} onClick={()=>move(i,-1)}>←</button><button disabled={i===frames.length-1} onClick={()=>move(i,1)}>→</button><button onClick={()=>duplicate(i)}>＋</button><button className="danger" onClick={()=>remove(f.id)}>×</button></div></article>)}</div>}</section>

      <section className="card"><h2>3. Movimento e qualidade</h2><div className="two-col"><label>Tipo de loop<select value={loopMode} onChange={e=>setLoopMode(e.target.value as LoopMode)}><option value="ping-pong">Ida e volta • recomendado</option><option value="linear">Sequência linear</option></select></label><label>Resolução<select value={size} onChange={e=>setSize(Number(e.target.value))}><option value="384">384×384 leve</option><option value="512">512×512 recomendada</option><option value="640">640×640 alta</option></select></label></div><label className="range">Tempo por quadro: <b>{delay} ms</b><input type="range" min="150" max="1200" step="50" value={delay} onChange={e=>setDelay(Number(e.target.value))}/></label><div className="two-col"><label>Pausa inicial: <b>{startPause} ms</b><input type="range" min="0" max="1200" step="50" value={startPause} onChange={e=>setStartPause(Number(e.target.value))}/></label><label>Pausa no topo/final: <b>{endPause} ms</b><input type="range" min="0" max="1200" step="50" value={endPause} onChange={e=>setEndPause(Number(e.target.value))}/></label></div><div className="path">Ciclo aproximado: <b>{(cycleMs/1000).toFixed(1)} segundos</b> • {playback.length} passos</div><div className="preview">{playback.length?<img src={playback[previewIndex%playback.length]?.dataUrl}/>:<div>Prévia aparecerá aqui</div>}</div></section>

      <section className="card"><h2>4. Finalizar</h2><button className="final-btn" disabled={working||frames.length<2} onClick={generateFinal}>{working?"Processando...":"Gerar GIF final e compartilhar"}</button><p className="message">{message}</p></section>

      <section className="card"><div className="library-head"><div><h2>Biblioteca</h2><p className="muted">Os novos itens guardam também os quadros e configurações.</p></div><b>{saved.length}</b></div>{saved.length===0?<div className="empty">Nenhum GIF salvo ainda.</div>:<div className="saved">{[...saved].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(item=><article key={item.id}><div><strong>{item.name}</strong><small>{item.category}/{item.slug} • {item.frames?.length??"antigo"} quadros • {(item.bytes.length/1024/1024).toFixed(2)} MB</small></div><div><button onClick={()=>shareBytes(item.bytes,`${item.slug}.gif`)}>Compartilhar</button><button className="danger" onClick={async()=>{await deleteGif(item.id);setSaved(await listSaved())}}>Apagar</button></div></article>)}</div>}<button className="zip-btn" disabled={!saved.length||working} onClick={exportZip}>Exportar ZIP completo para o Projeto Trincado</button></section>
    </main>
    <footer>v0.5 • Modo Original é o fluxo principal. Rascunho ficou separado para não ser confundido com o visual final.</footer>
  </div>
}
