import { Camera, Edit3, Eye, Globe2, Instagram, Save } from "lucide-react";
import { useState } from "react";
import { AppShell } from "../components/AppShell";
import { useAppState } from "../state/AppState";

export function ProfileScreen(){
 const {profile,setProfile}=useAppState(); const [saved,setSaved]=useState(false);
 const toggle=(key:keyof typeof profile.social)=>setProfile(p=>({...p,social:{...p.social,[key]:!p.social[key]}}));
 return <AppShell><div className="page-pad"><div className="page-heading"><h1>Meu perfil</h1><p>Gerencie suas informações e como você aparece para os outros.</p></div><section className="hero-card profile-hero"><div className="profile-avatar">HF</div><div className="profile-data"><h2>Hallan Fernando Lehrbach</h2><p>Matrícula: <b>6546</b></p><div className="profile-chips"><span>✓ Ativo</span><span>Idade 35</span><span>Masculino</span></div><div className="profile-actions"><button><Camera/> Editar foto</button><button><Edit3/> Editar dados</button></div></div></section>
 <section className="section-card public-settings"><div className="setting-header"><div className="round-icon green"><Globe2/></div><div><h2>Perfil público</h2><p>Defina as informações que deseja compartilhar com o público.</p></div><label className="switch"><input type="checkbox" checked={profile.publicProfile} onChange={()=>setProfile(p=>({...p,publicProfile:!p.publicProfile}))}/><span/></label></div><label className="bio-field"><b>Bio</b><textarea value={profile.bio} maxLength={150} onChange={(e)=>setProfile(p=>({...p,bio:e.target.value}))}/><small>{profile.bio.length}/150</small></label><SocialRow label="Instagram" value="@hallan.lehrbach" on={profile.social.instagram} toggle={()=>toggle('instagram')}/><SocialRow label="Facebook" value="Hallan Lehrbach" on={profile.social.facebook} toggle={()=>toggle('facebook')}/><SocialRow label="TikTok" value="@hallan.lehrbach" on={profile.social.tiktok} toggle={()=>toggle('tiktok')}/><SocialRow label="WhatsApp" value="(51) 99999-9999" on={profile.social.whatsapp} toggle={()=>toggle('whatsapp')}/></section>
 <section className="section-card preview-card"><div className="setting-header"><div className="round-icon neutral"><Eye/></div><div><h2>Prévia do perfil público</h2><p>Assim seu perfil será visto por outros alunos.</p></div></div><div className="public-preview"><div className="profile-avatar small">HF</div><div><h3>Hallan Fernando Lehrbach</h3><p>✓ Ativo • 35 anos • Masculino</p><span>{profile.bio}</span><div className="social-icons"><Instagram/><span>f</span><span>♪</span><span>☎</span></div></div></div></section><button className="primary-button" onClick={()=>{setSaved(true);setTimeout(()=>setSaved(false),1800)}}><Save/> Salvar perfil</button>{saved&&<div className="toast">Perfil salvo com sucesso.</div>}</div></AppShell>
}
function SocialRow({label,value,on,toggle}:{label:string;value:string;on:boolean;toggle:()=>void}){return <div className="social-row"><span className="social-mark">{label[0]}</span><div><b>{label}</b><small>{value}</small></div><label className="switch"><input type="checkbox" checked={on} onChange={toggle}/><span/></label></div>}
